ALTER TABLE properties
  ALTER COLUMN area      DROP NOT NULL,
  ALTER COLUMN rooms     DROP NOT NULL,
  ALTER COLUMN bathrooms DROP NOT NULL,
  ALTER COLUMN price     DROP NOT NULL;

ALTER TABLE properties
  ALTER COLUMN area      SET DEFAULT NULL,
  ALTER COLUMN rooms     SET DEFAULT NULL,
  ALTER COLUMN bathrooms SET DEFAULT NULL,
  ALTER COLUMN price     SET DEFAULT NULL;
